# .github/actions/setup-node/action.yml
name: 'Setup Node.js'
description: 'Sets up Node.js and installs dependencies'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22.9.0'
        cache: 'npm'
    - run: npm ci
      shell: bash
