services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/myapp
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=http://localhost:8080,http://127.0.0.1:8080
      - TEST_DATABASE_URL=mongodb://db_test:27017/myapp_test
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - node_modules:/app/node_modules

  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js
    command: mongod --bind_ip_all
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db_test
    environment:
      - DATABASE_URL=mongodb://db_test:27017/myapp_test
      - NODE_ENV=test
      - JWT_SECRET=test_secret
      - CORS_ORIGIN=http://localhost:8080,http://127.0.0.1:8080
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  mongodb_data:
  mongodb_test_data:
  node_modules:
