name: Branch Workflow

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_pr:
    runs-on: ubuntu-latest
    outputs:
      has_pr: ${{ steps.check_pr.outputs.has_pr }}
    steps:
      - uses: actions/checkout@v4
      - name: Check if PR exists
        id: check_pr
        run: |
          PR_EXISTS=$(gh pr list --head ${{ github.ref_name }} --json number --jq 'length')
          echo "has_pr=$PR_EXISTS" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    needs: check_pr
    if: needs.check_pr.outputs.has_pr == '0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-and-cache
        with:
          cache-key-prefix: branch-${{ github.ref_name }}
      - name: Run unit tests
        run: NODE_OPTIONS=--max_old_space_size=4096 npm run test:unit
