name: Branch CI

on:
  push:
    branches-ignore:
      - main

jobs:
  check_pr:
    runs-on: ubuntu-latest
    outputs:
      has_pr: ${{ steps.check_pr.outputs.has_pr }}
    steps:
      - uses: actions/checkout@v4
      - name: Check if PR exists
        id: check_pr
        run: |
          PR_EXISTS=$(gh pr list --head ${{ github.ref_name }} --json number --jq 'length')
          echo "has_pr=$PR_EXISTS" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    needs: check_pr
    if: needs.check_pr.outputs.has_pr == '0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: |
          NODE_OPTIONS=--max_old_space_size=4096 npm run test:unit
