name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
      GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
      GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
      GITHUB_TOKEN: ''
      GITHUB_OWNER: ''
      GITHUB_REPO: ''
      PORT: ${{ secrets.PORT }}
      CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      LOG_LEVEL: info
      LOG_FORMAT: json
      LOG_FILE_PATH: './logs'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.0'
      - name: Clean install
        run: |
          rm -rf node_modules
          npm ci --legacy-peer-deps
      - name: Debug TypeScript Config
        run: npx tsc --showConfig
      - name: Debug Webpack Config
        run: npx webpack --config webpack.config.prod.js --stats-error-details
      - name: Build
        run: npx webpack --config webpack.config.prod.js

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: github.event_name == 'push'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push test image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/your-image-name:test
          build-args: |
            NODE_ENV=test
            # ... other build arguments

      - name: Run Tests
        run: |
          docker-compose -f docker-compose.yml up --exit-code-from test-runner
          args: -f docker-compose.yml up --exit-code-from test-runner
        env:
          GOOGLE_SHEETS_ID: 'test-id'
          GOOGLE_SHEETS_CLIENT_EMAIL: 'test-user'
          GOOGLE_SHEETS_PRIVATE_KEY: 'test-key'
          GITHUB_TOKEN: 'github_pat_test'
          GITHUB_OWNER: 'test-user'
          GITHUB_REPO: 'test-org/test-repo'
          PORT: 3000
          CORS_ORIGIN: http://localhost:3000,null
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          LOG_LEVEL: info
          LOG_FORMAT: json
          LOG_FILE_PATH: './logs'
