name: PR Workflow

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-and-cache
        with:
          cache-key-prefix: pr-${{ github.event.pull_request.number }}

  test-unit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            dist
            node_modules
          key: ${{ runner.os }}-pr-${{ github.event.pull_request.number }}-${{ github.sha }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run unit tests
        run: NODE_OPTIONS=--max_old_space_size=4096 npm run test:unit

  e2e-test:
    needs: [build, test-unit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-setup
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Debug environment variables
        run: |
          echo "DATABASE_URL is set: ${{ secrets.DATABASE_URL != '' }}"
          echo "GOOGLE_SHEETS_ID is set: ${{ secrets.GOOGLE_SHEETS_ID != '' }}"
          echo "GOOGLE_SHEETS_CLIENT_EMAIL is set: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL != '' }}"
          echo "GOOGLE_SHEETS_PRIVATE_KEY is set: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY != '' }}"
          echo "REPO_TOKEN is set: ${{ secrets.REPO_TOKEN != '' }}"
          echo "REPO_OWNER is set: ${{ secrets.REPO_OWNER != '' }}"
          echo "REPO_REPO is set: ${{ secrets.REPO_REPO != '' }}"
      - name: Build and run E2E tests with Docker Compose
        env:
          API_URL: http://app-test:${{ secrets.PORT }}
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
          GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
          GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          LOG_FILE_PATH: ./logs
          LOG_FORMAT: json
          LOG_LEVEL: debug
          MONGO_CONNECT_TIMEOUT_MS: 10000
          MONGO_INITDB_ROOT_PASSWORD: example
          MONGO_INITDB_ROOT_USERNAME: root
          NODE_ENV: test
          PORT: ${{ secrets.PORT }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_REPO: ${{ secrets.REPO_REPO }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          docker-compose --profile e2e-test build
          docker-compose --profile e2e-test up --abort-on-container-exit --exit-code-from e2e-test-runner
      - name: Display logs
        if: always()
        run: docker-compose --profile e2e-test logs app-test

  check-breaking-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for breaking changes
        run: |
          if git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }} | grep -q "BREAKING CHANGE"; then
            echo "::warning ::This PR contains breaking changes. Please review carefully."
          fi
